app/src/Entity/Trait/CreatedAtTrait.php
<?php

namespace App\Entity\Trait;

use Doctrine\ORM\Mapping as ORM;

trait CreatedAtTrait
{
    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

app/src/Entity/Trait/UpdatedAtTrait.php
<?php

namespace App\Entity\Trait;

use Doctrine\ORM\Mapping as ORM;

trait UpdatedAtTrait
{
    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $updated_at = null;

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

app/src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\UpdatedAtTrait;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
class Trick
{
    use CreatedAtTrait;
    use UpdatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\NotBlank(message: 'Le titre du trick ne peut pas être vide')]
    #[Assert\Length(
        min: 3,
        max: 200,
        minMessage: 'Le titre du trick doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Le titre du trick doit contenir au maximum {{ limit }} caractères'
    )]
    private ?string $title = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 3000)]
    #[Assert\NotBlank(message: 'La description du trick ne peut pas être vide')]
    #[Assert\Length(
        min: 10,
        max: 3000,
        minMessage: 'La description du trick doit contenir au moins {{ limit }} caractères',
        maxMessage: 'La description du trick doit contenir au maximum {{ limit }} caractères'
    )]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'trick')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TrickCategory $category = null;

    #[ORM\ManyToOne(inversedBy: 'trick')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class)]
    private Collection $comment;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: TrickImage::class, orphanRemoval: true, cascade: ['persist'])]
    private $image;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: TrickVideo::class, orphanRemoval: true, cascade: ['persist'])]
    private $video;

    #[ORM\ManyToOne(inversedBy: 'trick')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $updated_by = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
        $this->comment = new ArrayCollection();
        $this->image = new ArrayCollection();
        $this->video = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?TrickCategory
    {
        return $this->category;
    }

    public function setCategory(?TrickCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?User $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TrickImage>
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(TrickImage $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image->add($image);
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(TrickImage $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TrickVideo>
     */
    public function getVideo(): Collection
    {
        return $this->video;
    }

    public function addVideo(TrickVideo $video): self
    {
        if (!$this->video->contains($video)) {
            $this->video->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(TrickVideo $video): self
    {
        if ($this->video->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

}

app/src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Un compte existe déjà avec ce nom d\'utilisateur')]
#[UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cette adresse email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CreatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: 'Le nom d\'utilisateur ne peut pas être vide')]
    #[Assert\Length(
        min: 4,
        max: 180,
        minMessage: 'Le nom d\'utilisateur doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Le nom d\'utilisateur doit contenir au maximum {{ limit }} caractères'
    )]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\NotBlank(message: 'L\'adresse email ne peut pas être vide')]
    #[Assert\Email(message: 'L\'adresse email n\'est pas valide')]
    private ?string $email = null;

    #[ORM\Column(length: 255, options: ['default' => 'default.webp'])]
    private ?string $profile_picture = 'default.webp';

    #[ORM\Column(type: 'boolean')]
    private ?bool $is_verified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Trick::class)]
    private Collection $trick;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comment;

    public function __construct()
    {
        $this->trick = new ArrayCollection();
        $this->comment = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    /**
     * @return Collection<int, Trick>
     */
    public function getTrick(): Collection
    {
        return $this->trick;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->trick->contains($trick)) {
            $this->trick->add($trick);
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->trick->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

app/templates/trick/_form.html.twig
{{ form_start(trickForm) }}
    {# if is editting page #}
    {% if app.request.attributes.get('_route') == 'trick_update' %}
        {% include "trick/_form_media.html.twig" %}
    {% endif %}

    {{ form_row(trickForm.title) }}
    {{ form_row(trickForm.description) }}
    {{ form_row(trickForm.category) }}
    {{ form_row(trickForm.image) }}

    <div class="form-videos">
        {{ form_label(trickForm.videos) }}

        <div id="videos-container"
            data-prototype="{{ form_row(trickForm.videos.vars.prototype)|e }}"
            data-index="{{ trickForm.videos|length }}">
            <button type="button" class="add-video btn" data-target="#videos-container">
                Ajouter une vidéo
            </button>
            {% for video in trickForm.videos %}
                <div class="video-item">
                    <div class="form-group">
                        {{ form_row(video) }}
                        {{ form_errors(video) }}
                    </div>
                    <button type="button" class="btn remove-video">Supprimer</button>
                </div>
            {% endfor %}
        </div>
    </div>
    {{ form_errors(trickForm.videos) }}
    {{ form_widget(trickForm.videos) }}

    {# if is editting page #}
    {% if app.request.attributes.get('_route') == 'trick_update' %}
        <div class="tricks-content-btn d-flex justify-content-end">
            <button type="submit" class="btn update">{{ button_label|default('Modifier le trick') }}</button>
            <a class="btn delete mx-3 delete-trick-modal"
                data-url="{{ path('trick_delete', {slug: trick.slug}) }}"
                data-confirm-message="Êtes-vous sûr de vouloir supprimer le trick '{{ trick.title }}' ?">
                Supprimer le trick
            </a>
        </div>
    {% else %}
        <div class="tricks-content-btn d-flex justify-content-center mt-4 mb-4">
            <button type="submit" class="btn create">{{ button_label|default('Créer le trick') }}</button>
        </div>
    {% endif %}
{{ form_end(trickForm) }}

app/templates/trick/_form_media.html.twig
<!-- Medias -->
<div class="container medias pt-4">
    <div class="row hidden-md-up row-cols-md-2 row-cols-lg-3">
        {% for image in trick.image %}
            <!-- Images -->
            <div class="media-block d-flex flex-column mb-4">
                <div class="col">
                    <div class="card">
                        <img class="card-img-top" src="{{ asset('assets/uploads/tricks/mini/300x300-' ~ image.name) }}" alt="Image de {{ trick.title }}">
                    </div>
                </div>
                <div class="medias-links d-flex flex-row justify-content-between align-items-center">
                    <a class="update-trick-image-modal"
                        data-image-name="{{ image.name }}"
                        data-trick-id="{{ trick.id }}"
                        data-url="{{ path('trick_update', {slug: trick.slug}) }}">
                        <i class="fa-sharp fa-solid fa-pencil"></i>
                    </a>
                    <a class="delete-medias-modal" href="#"
                        data-delete
                        data-url="{{ path('trick_image_delete', {slug: trick.slug, id: image.id}) }}"
                        data-redirect="{{ path('trick_update', {slug: trick.slug}) }}"
                        data-confirm-message="Êtes-vous sûr de vouloir supprimer cette image ?"
                        data-token="{{ csrf_token('delete' ~ image.id) }}">
                        <i class="fa-regular fa-trash-can"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
        {% for video in trick.video %}
            <!-- Videos -->
            <div class="media-block d-flex flex-column mb-4">
                <div class="col">
                    <div class="card">
                        <iframe class="card-img-top" src="{{ video.url }}"></iframe>
                    </div>
                </div>
                <div class="medias-links d-flex flex-row justify-content-between align-items-center">
                    <a class="update-trick-video-modal"
                        data-video-url="{{ video.url }}"
                        data-trick-id="{{ trick.id }}"
                        data-url="{{ path('trick_update', {slug: trick.slug}) }}">
                        <i class="fa-sharp fa-solid fa-pencil"></i>
                    </a>
                    <a class="delete-medias-modal" href="#"
                    data-delete
                    data-url="{{ path('trick_video_delete', {slug: trick.slug, id: video.id}) }}"
                    data-redirect="{{ path('trick_update', {slug: trick.slug}) }}"
                    data-confirm-message="Êtes-vous sûr de vouloir supprimer cette vidéo ?"
                    data-token="{{ csrf_token('delete' ~ video.id) }}">
                        <i class="fa-regular fa-trash-can"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<!-- Mobile Medias (Button trigger modal) -->
{% if trick.image.count() >= 1 or trick.video.count() >= 1 %}
    <div class="mobile-medias d-flex justify-content-center pt-4">
        <button type="button" class="btn" data-toggle="modal" data-target="#mobileMediasModal">Afficher les médias</button>
    </div>
{% endif %}

<!-- Mobile Medias Modal -->
<div class="modal fade" id="mobileMediasModal" tabindex="-1" role="dialog" aria-labelledby="mobileMediasModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mobileMediasModalLabel">Gestion des médias</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <!-- Images -->
                    {% for image in trick.image %}
                        <div class="media-block">
                            <div class="my-4">
                                <img class="card-img-top" src="{{ asset('assets/uploads/tricks/mini/300x300-' ~ image.name) }}" alt="Image de {{ trick.title }}">
                            </div>
                            <div class="mobile-medias-links d-flex flex-row justify-content-between align-items-center">
                                <a class="update-trick-image-modal"
                                    data-image-name="{{ image.name }}"
                                    data-trick-id="{{ trick.id }}"
                                    data-url="{{ path('trick_update', {slug: trick.slug}) }}">
                                    <i class="fa-sharp fa-solid fa-pencil"></i>
                                </a>
                                <a class="delete-medias-modal" href="#"
                                    data-delete
                                    data-url="{{ path('trick_image_delete', {slug: trick.slug, id: image.id}) }}"
                                    data-redirect="{{ path('trick_update', {slug: trick.slug}) }}"
                                    data-confirm-message="Êtes-vous sûr de vouloir supprimer cette image ?"
                                    data-token="{{ csrf_token('delete' ~ image.id) }}">
                                <i class="fa-regular fa-trash-can"></i>
                            </a>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                    <!-- Videos -->
                    {% for video in trick.video %}
                        <div class="media-block">
                            <div class="my-4">
                                <iframe height="406" class="card-img-top" src="{{ video.url }}"></iframe>
                            </div>
                            <div class="mobile-medias-links d-flex flex-row justify-content-between align-items-center">
                                <a class="update-trick-video-modal"
                                    data-video-url="{{ video.url }}"
                                    data-trick-id="{{ trick.id }}"
                                    data-url="{{ path('trick_update', {slug: trick.slug}) }}">
                                    <i class="fa-sharp fa-solid fa-pencil"></i>
                                </a>
                                <a class="delete-medias-modal" href="#"
                                    data-delete
                                    data-url="{{ path('trick_video_delete', {slug: trick.slug, id: video.id}) }}"
                                    data-redirect="{{ path('trick_update', {slug: trick.slug}) }}"
                                    data-confirm-message="Êtes-vous sûr de vouloir supprimer cette vidéo ?"
                                    data-token="{{ csrf_token('delete' ~ video.id) }}">
                                    <i class="fa-regular fa-trash-can"></i>
                                </a>
                            </div>
                            <hr>
                        </div>

                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="medias-modal-btn btn btn-secondary" data-dismiss="modal">Retour</button>
            </div>
        </div>
    </div>
</div>

<!-- Trick infos -->
<div class="infos d-flex flex-row justify-content-center mb-4">
    <span>Créer le {{ trick.createdAt|date('d/m/Y') }} par {{ trick.author.username }}</span>
    <span class="vertical-line"></span>
    {% if (trick.createdAt != trick.updatedAt) and trick.updatedBy.username != null %}
        <span >Modifier le {{ trick.updatedAt|date('d/m/Y') }} par {{ trick.updatedBy.username }}</span>
    {% else %}
        <span >Ce trick n'a jamais été modifié</span>
    {% endif %}
</div>

app/templates/trick/_modal_delete.html.twig
<!-- Modal to confirm tick deleted -->
<div id="confirm-modal">
    <div class="modal-content">
        <p id="confirm-message"></p>
        <div class="d-flex flex-row justify-content-center">
            <button id="confirm-yes" class="btn confirm-modal-validate mx-2">Confirmer</button>
            <button id="confirm-no" class="btn confirm-modal-cancel mx-2">Annuler</button>
        </div>
    </div>
</div>

app/templates/trick/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un Trick / SnowTricks{% endblock %}

{% block body %}
    <section class="create-tricks d-flex align-items-center">
        <!-- Form -->
        <div class="tricks-content container mt-4">
            {% include "trick/_form.html.twig" %}
        </div>
    </section>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/formVideos.min.js') }}" defer></script>
{% endblock %}

app/templates/trick/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.title }} / Snowtrick{% endblock %}

{% block body %}
<section class="details-tricks pb-5">
    <!-- Main image -->
    <div class="tricks-img-main">
        {% if trick.image.first() %}
            <img class="card-img-top" src="{{ asset('assets/uploads/tricks/' ~ trick.image[0].name) }}" alt="Image de {{ trick.title }}">
        {% else %}
            <img class="card-img-top" src="{{ asset('assets/uploads/tricks/default.webp') }}" alt="Image de {{ trick.title }}">
        {% endif %} 
        <span>{{ trick.title }}</span>
        {% if (app.user and app.user.id == trick.author.id) or (app.user and isAdmin == true) %}
            <div class="links">
                <a href="{{ path('trick_update', {slug: trick.slug}) }}" class="update">
                    <i class="fa-sharp fa-solid fa-pencil"></i>
                </a>
                <a class="delete delete-trick-modal"
                    data-url="{{ path('trick_delete', {slug: trick.slug}) }}" 
                    data-confirm-message="Êtes-vous sûr de vouloir supprimer le trick '{{ trick.title }}' ?">
                    <i class="fa-regular fa-trash-can"></i>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- Modal to confirm tick deleted -->
    {% include "trick/_modal_delete.html.twig" %}

    <!-- Medias -->
    <div class="container medias pt-4">
        <div class="row hidden-md-up row-cols-md-2 row-cols-lg-3">
            {% for image in trick.image %}
                <div class="d-flex flex-column mb-4">
                    <div class="col">
                        <div class="card">
                            <img class="card-img-top" src="{{ asset('assets/uploads/tricks/mini/300x300-' ~ image.name) }}" alt="Image de {{ trick.title }}">
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% for video in trick.video %}
                <div class="d-flex flex-column mb-4">
                    <div class="col">
                        <div class="card">
                            <iframe height="250" class="card-img-top" src="{{ video.url }}" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Mobile Medias (Button trigger modal) -->
    {% if trick.image.count() >= 1 or trick.video.count() >= 1 %}
        <div class="mobile-medias d-flex justify-content-center pt-4">
            <button type="button" class="btn" data-toggle="modal" data-target="#mobileMediasModal">Afficher les médias</button>
        </div>
    {% endif %}


    <!-- Mobile Medias Modal -->
    <div class="modal fade" id="mobileMediasModal" tabindex="-1" role="dialog" aria-labelledby="mobileMediasModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mobileMediasModalLabel">Visualisation des médias</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Images -->
                    {% for image in trick.image %}
                        <div class="my-4">
                            <img height="250" class="card-img-top" src="{{ asset('assets/uploads/tricks/mini/300x300-' ~ image.name) }}" alt="Image de {{ trick.title }}">
                        </div>
                    {% endfor %}
                    <hr>
                    <!-- Videos -->
                    {% for video in trick.video %}
                        <div class="my-4">
                            <iframe height="250" class="card-img-top" src="{{ video.url }}" allowfullscreen></iframe>
                        </div>
                    {% endfor %}
                    <hr>
                </div>
                <div class="modal-footer">
                    <button type="button" class="medias-modal-btn btn btn-secondary" data-dismiss="modal">Retour</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Content -->
    <div class="tricks-content container mt-4">
        <span class="description fw-bolder">{{ trick.description }}</span>
        <div class="infos d-flex flex-row justify-content-center mt-5">
            <span class="mx-4">Catégorie : {{ trick.category.name }}</span>
            <span class="mx-2">Créer le {{ trick.createdAt|date('d/m/Y') }} par {{ trick.author.username }}</span>
            {% if (trick.createdAt != trick.updatedAt) and trick.updatedBy != null %}
                <span class="mx-2">Modifier le {{ trick.updatedAt|date('d/m/Y') }} par {{ trick.updatedBy.username }}</span>
            {% endif %}
        </div>
        {% if app.user %}
            <hr>
            <div class="post-comment my-4">
                {{ form_start(createCommentForm) }}
                <div class="d-flex flex-row justify-content-center ">
                    {{ form_row(createCommentForm.content) }}
                    <button type="submit" class="btn create-comment-btn mx-2">Publier le commentaire</button>
                </div>
                {{ form_end(createCommentForm) }}
            </div>
        {% endif %}
        <div class="comments" id="comments">
            {% if comments %}
            <hr>
                {% for comment in comments.data %}
                    <div class="d-flex flex-row justify-content-start mt-4">
                        {% if comment.author.profilePicture == 'default.webp' %}
                            <img src="{{ asset('assets/uploads/users/default.webp') }}" alt="Photo de profil de {{ comment.author.username }}" class="img-circle">
                        {% else %}
                            <img src="{{ asset('assets/uploads/users/mini/90x90-' ~ comment.author.profilePicture) }}" alt="Photo de profil de {{ comment.author.username }}" class="img-circle">
                        {% endif %}
                        <div class="d-flex flex-column">
                            <span class="px-2 fw-bolder">{{ comment.content }}</span>
                            <span class="px-2 text-muted">
                                Publier le {{ comment.createdAt|date('d/m/Y') }} par {{ comment.author.username }}
                                {% if (app.user and app.user.id == comment.author.id) or (app.user and isAdmin == true) %}
                                    <a href="{{ path('trick_delete_comment', {slug: trick.slug, id: comment.id}) }}"> 
                                        <span class="delete-comment">| Supprimer le commentaire</span>
                                    </a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                {% endfor %}
                {% set path = 'trick_details' %}
                {% set anchor = 'comments' %}
                {% set slug = trick.slug %}
                {% set pages = comments.pages %}
                {% set currentPage = comments.page %}
                {% include "_partials/_pagination.html.twig" %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/deleteTrickConfirm.min.js') }}" defer></script>
{% endblock %}